### PR TITLE
:pencil: Add contact social links; minor wording changes 

### PR DESCRIPTION
**Pull request by williln**

### CODE REVIEW

**Comment by frankwiles** [comment]
Whoops small issue with `setup.py` assuming `README.rst` exists. Need to adjust that for the tests to pass.

**Comment by williln** [comment]
@frankwiles I adjusted that but some tests are still failing...

**Comment by jefftriplett** [comment]
Travis is being weird. 

`  py34-dj18: commands succeeded` works fine for me.

**Comment by jefftriplett** [comment]
@williln do you mind resolving the conflicts here and merging master back in? That should fix things.

**Comment by williln** [comment]
@jefftriplett I think this can just be closed? Looks like most of this was taken care of in another PR. This PR initially was replacing the README.rst with the README.md, but since that got done in another PR I can't easily ID the wording changes I had. I'll open another PR for the red pen stuff later.

**Pull request merged**
