### PR TITLE
Use packaging.version where available

### PR DESCRIPTION
**Pull request by offbyone**
Fixes: https://github.com/revsys/django-test-plus/issues/209

### CODE REVIEW

**Comment by offbyone** [comment]
Note, I could not run the tests locally, so I'm hoping CI bears out my work here:

```
  File "/Users/offby1/projects/django-test-plus/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1592, in getini
    self._inicache[name] = val = self._getini(name)
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/projects/django-test-plus/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1651, in _getini
    return self._getini_unknown_type(name, type, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/offby1/projects/django-test-plus/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1599, in _getini_unknown_type
    raise ValueError(msg, value)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: ('unknown configuration type: pathlist', 'test_project/')
```

(I'm not sure what's going on there, and I'll only dig into it if I need to spend a bunch of iterations on this :) )

**Comment by offbyone** [comment]
#211 will allow these tests to run

**Comment by jefftriplett** [comment]
I think we could safely `packaging; python_version >= '3.7'` to `setup.cfg::setup_requires`.

(side-note: I don't see a reason to not drop 3.6, 3.7, and 3.8 if we are going to do a major upgrade)

**Comment by jefftriplett** [comment]
@offbyone thank you!

**Pull request merged**
