### PR TITLE
:snake: Update testing matrix to support 3.7 and README updates

### PR DESCRIPTION
**Pull request by jefftriplett**

### CODE REVIEW

**Comment by jefftriplett** [comment]
@frankwiles looks like Travis isn't quite ready to test yet: https://travis-ci.org/revsys/django-test-plus/jobs/405984738

**Comment by frankwiles** [comment]
heh I guess you can wait to merge this until it is.  I wonder if they have an ETA?

**Comment by jefftriplett** [comment]
maybe? https://github.com/travis-ci/travis-ci/issues/9815

**Comment by frankwiles** [comment]
Yeah that seems kinda shaky, I'd just wait for them to officially support 3.7 in hopefully a few days/weeks

**Comment by jefftriplett** [comment]
@frankwiles this should be good to go. Can merge tomorrow: https://travis-ci.org/revsys/django-test-plus/builds/445357567

**Pull request merged**
