### PR TITLE
:tractor: Initial GitHub Actions integration

### LINKED ISSUE #162: 🚜  Migrate CI to GitHub Actions
@fcurella should we keep Tox or do you mind if I use GitHub Action's Matrix feature?

### PR DESCRIPTION
**Pull request by jefftriplett**
Fixes #162

This pull request: 
- Adds GHA support (via Matrix)
- Adds 3.10 support
- Drops Travis
- Drops 3.5 in testing since it's well past EOL
- Drops tox
- Updates setup.cfg to make optional requirements installable

Could do:
- Delete tox.ini, but I left it in case it's useful locally. 

Follow up:
- Adding DRF Matrix support since that's opinionated. #168

### CODE REVIEW

**Comment by fcurella** [comment]
Why wouldn't we test against DRF in all jobs? I would just add `djangorestframework` to the `test_requires`

**Comment by jefftriplett** [comment]
> Why wouldn't we test against DRF in all jobs? I would just add `djangorestframework` to the `test_requires`

I noticed the old tests tested without it (see tox too for example) so I assumed we needed it. If it's not a big deal, then that checks a big ✅

**Comment by jefftriplett** [comment]
@fcurella @frankwiles do either of you see an issue dropping Python 3.5? It's been EOL since December and pip + pytest no longer support it (not that I can't use older versions).

**Comment by fcurella** [comment]
Totally fine with dropping Py 3.5

**Comment by frankwiles** [comment]
Yeah I'm fine with dropping 3.5, hell I'm ok with no longer even testing against 3.6 or at least not letting 3.6 compatibility cause us any work.

**Pull request merged**
