### PR TITLE
Use pytest's native python path support

### PR DESCRIPTION
**Pull request by offbyone**
This is added in Pytest 7

Fixes my failure to locally CI as mentioned in https://github.com/revsys/django-test-plus/pull/210#issuecomment-2081532869

### CODE REVIEW

**Review by fcurella — APPROVED** [review]
Pytest 7 was released in Feb 2022, I think it should be safe to require >= 7.0

**Comment by offbyone** [comment]
@fcurella would you be in a position to merge this? With this in, #210 will work, and with #210 in, I can upgrade to 3.12 :D

**Comment by fcurella** [comment]
I can merge this, but I will consider it a breaking change and I'd like to give it some more visibility.

cc @frankwiles @jefftriplett

**Comment by jefftriplett** [comment]
I'll ping @frankwiles and ask him today. In theory, bumping to a major version and dropping the dependency feels like the right thing to do. If this breaks for someone, then we can pin to the previous version since it's been stable for years.

**Comment by offbyone** [comment]
Fair! I think in my head I considered Pytest to be a "test dependency" but... so is this one, so they're sharing a dependency closure :D 

It's obvious in hindsight.

**Comment by jefftriplett** [comment]
I'm merging these to get ready for a release. We hope to get them both in tomorrow, but the repo might be a little off for a bit.

**Pull request merged**
